[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
auto_detect_solc = false

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
localhost = "http://127.0.0.1:8545"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
multiline_func_header = "all"
sort_imports = true